name: Linux

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*
    tags:
      - 2.*
  pull_request:
    branches: [ "trunk", "2.4.x" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*

env:
  MARGS: "-j2"
  CFLAGS: "-g"
  # This will need updating as the ubuntu-latest image changes:
  PHP_FPM: "/usr/sbin/php-fpm8.1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MOD_TLS test suite
            config: --enable-mods-shared=reallyall --with-mpm=event --enable-mpms-shared=event
            pkgs: curl python3-pytest nghttp2-client python3-cryptography python3-requests python3-multipart python3-filelock python3-websockets cargo cbindgen
            env: |
              APR_VERSION=1.7.4
              APU_VERSION=1.6.3
              APU_CONFIG="--with-crypto"
              RUSTLS_VERSION="v0.14.0"
              NO_TEST_FRAMEWORK=1
              TEST_INSTALL=1
              TEST_MOD_TLS=1
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NOTEST_CFLAGS: ${{ matrix.notest-cflags }}
      CONFIG: ${{ matrix.config }}
    name: ${{ matrix.name }}
    steps:
    - name: Set environment variables
      run: |
        echo "${{ matrix.env }}" >> $GITHUB_ENV
        echo JOBID=`echo "${{ matrix.notest-cflags }} ${{ matrix.env }} ${{ matrix.config }}'"| md5sum - | sed 's/ .*//'` >> $GITHUB_ENV
    # https://github.com/actions/runner-images/issues/9491#issuecomment-1989718917
    - name: Workaround ASAN issue in Ubuntu 22.04
      run: sudo sysctl vm.mmap_rnd_bits=28
    - name: apt refresh
      run: sudo apt-get -o Acquire::Retries=5 update
    - name: Install prerequisites
      run: sudo apt-get install -o Acquire::Retries=5
                    cpanminus libtool-bin libapr1-dev libaprutil1-dev
                    liblua5.3-dev libbrotli-dev libcurl4-openssl-dev     
                    libnghttp2-dev libjansson-dev libpcre2-dev gdb
                    perl-doc libsasl2-dev ${{ matrix.pkgs }}
    - uses: actions/checkout@v4
    - name: Cache installed libraries
      uses: actions/cache@v4
      with:
        path: ~/root
        key: cache-libs-${{ env.JOBID }}
    - name: Cache CPAN modules
      uses: actions/cache@v4
      with:
        path: ~/perl5
        key: cache-cpan-${{ env.JOBID }}
    - name: Configure environment
      run: ./test/travis_before_linux.sh
      timeout-minutes: 15
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: config.log-${{ env.JOBID }}
        path: |
          /home/runner/build/**/config.log
    - name: Build and test
      run: ./test/travis_run_linux.sh
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: error_log-${{ env.JOBID }}
        path: test/perl-framework/t/logs/error_log

